backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/homepage/index.md'
        label: 'Homepage'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Hero', name: 'hero', widget: 'image' }
          - { label: 'Video', name: 'video', widget: 'file' }
          - { label: 'Image 1', name: 'image1', widget: 'image' }
          - { label: 'Image 2', name: 'image2', widget: 'image' }
          - { label: 'Image 3', name: 'image3', widget: 'image' }
          - { label: 'Footer', name: 'footer', widget: 'image' }
      - name: 'collection'
        label: 'Collection Page'
        file: 'src/pages/collection/index.md'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'collection-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Link', name: 'link', widget: 'string' }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Cover', name: 'cover', widget: 'image' }
          - { label: 'Intro', name: 'intro', widget: 'markdown' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/privacy/index.md'
        label: 'Privacy'
        name: 'privacy'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'privacy-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/cookie/index.md'
        label: 'Cookie'
        name: 'cookie'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'cookie-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
